### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by navierula** [shl83/TomeRater#8]
Valid Python Code (3/4)
Code was written in an organized way and for the most part, ran smoothly. There were some minor syntax errors, though.

Implementation of Project Requirements (4/4)
Code produces the suite of functions and classes required of it and calls them in an appropriate order.

Software Architecture (4/4)
Code is separated into distinct classes and functions each which are invoked for their own purposes. 

Uses Python Language Features (4/4)
Code uses language features appropriately. If a task can be solved with a Python language feature, it is.

**Comment by shl83** [comment]
Hi Navierula, thanks  so much for the feedback. I've attempted to solve the issues. Now when I run populate.py, I get this error:

====
Traceback (most recent call last):
  File "populate.py", line 9, in <module>
    nonfiction1 = Tome_Rater.create_non_fiction("Automate the Boring Stuff", "Python", "beginner", 1929452)
  File "/Users/yingyinglin/Desktop/Codecadamy/TomeRater/TomeRater.py", line 131, in create_non_fiction
    non_fiction = Non_Fiction(title, subject, isbn)
TypeError: __init__() missing 1 required positional argument: 'isbn'
====

I can't seem to solve it. I did include the 'isbn' in the init method.

**Comment by shl83** [comment]
I got that fixed, working on other issues now.

**Comment by shl83** [comment]
Hi navierula,

When I execute the populate.py file, it wrongly responds that no users exists:

No user with email marvin@mit.edu!
No user with email marvin@mit.edu!
No user with email marvin@mit.edu!

I can't seem to find what the issue is. Can you give me some guidance?

Regards,

**Comment by navierula** [comment]
Great job on fixing the previous error! As for the email error, it must be the case that the user does not exist, otherwise, that line would not print. Have you double-checked this?

**Comment by shl83** [comment]
If I understand it correctly populate.py first create books and users, and afterwards it adds books to users with a rating. So if the user doesn't exist, I think tomerater.py isn't fully working?

Here's the original populate.py code:
https://github.com/shl83/TomeRater/blob/master/populate.py

When I run this file, this is the full response in my Terminal:

this book’s ISBN has been updated
No user with email marvin@mit.edu!
No user with email marvin@mit.edu!
No user with email marvin@mit.edu!
No user with email alan@turing.com!
No user with email alan@turing.com!
No user with email alan@turing.com!
No user with email alan@turing.com!
No user with email alan@turing.com!
No user with email marvin@mit.edu!
No user with email marvin@mit.edu!
No user with email david@computation.org!
Most positive user:
None
Highest rated book:
None
Most read book:
None
